### ISSUE TITLE
Adding items

### ISSUE THREAD

**Issue by owalk** [m-one-w/M1WEngine#113]
<a href="https://github.com/Sean-Nishi"><img src="https://avatars.githubusercontent.com/u/22729669?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Sean-Nishi](https://github.com/Sean-Nishi)**
_Monday Dec 18, 2023 at 19:24 GMT_
_Originally opened as https://github.com/Sean-Nishi/M1Wengine/issues/293_

----

- [ ] add Justin's Milk #265 
- [ ] add chest #259 
- [ ] add potion item #257 
- [ ] add shoe item #188 
- [ ] add coin item #189
