### ISSUE TITLE
Overarching story for Levels

### ISSUE THREAD

**Issue by owalk** [m-one-w/M1WEngine#114]
<a href="https://github.com/Sean-Nishi"><img src="https://avatars.githubusercontent.com/u/22729669?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Sean-Nishi](https://github.com/Sean-Nishi)**
_Monday Dec 18, 2023 at 19:28 GMT_
_Originally opened as https://github.com/Sean-Nishi/M1Wengine/issues/294_

----

- [ ] design basic level for each level type #266 
- [ ] add hints to levels #271 
- [ ] pan camera across level at start #268 
- [ ] display level prompt #269 
- [ ] ending conditions for current level #254 
- [ ] Add different level types #267
