### ISSUE TITLE
Update file naming and add decorators and setters/gettings

### ISSUE THREAD

**Issue by owalk** [m-one-w/M1WEngine#118]
<a href="https://github.com/Sean-Nishi"><img src="https://avatars.githubusercontent.com/u/22729669?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Sean-Nishi](https://github.com/Sean-Nishi)**
_Wednesday Dec 20, 2023 at 18:10 GMT_
_Originally opened as https://github.com/Sean-Nishi/M1Wengine/issues/300_

----

- [x] change CamelCase to snake_case #179
- [ ] add property decorators to all vars #276 
- [ ] update all var names #221
- [x] update file naming convention #148
